- packages/kurt-open-ai/tsconfig.json
This was missing, causing declarations not to built for the public package. This commit fixes that by enabling the setting.
The other packages already had this setting correct.
> build: add missing declarations enablement to kurt-open-ai tsconfig

- .github/workflows/ci.yaml
This constitutes an important security protection.
Prior to this commit, a malicious actor could craft a malicious PR to exfitrate our `NPM_TOKEN` from GitHub Actions, *even if we don't merge the PR*, because the secret was available whenever GitHub Actions was running on this repo.
There is some protection we already had in place, in that first-time contributors would need to have approval from us before GitHub Actions would run CI code from their forks. However, this defense can still be breached with a bit of patience from the attacker - the malicious first-contributor only needs to issue one innocuous PR (e.g. a simple documentation improvement that is likely to be approved and merged) before then filing the malicious PR that exfiltrates the secret before we'd have any chance to react …
> ci: use an environment-locked secret for NPM_TOKEN in CI publish step

- packages/kurt-open-ai/spec/KurtOpenAI.spec.ts
- packages/kurt-open-ai/src/KurtOpenAI.ts
- packages/kurt-open-ai/src/index.ts
- packages/kurt-vertex-ai/spec/KurtVertexAI.spec.ts
- packages/kurt-vertex-ai/src/KurtVertexAI.ts
- packages/kurt-vertex-ai/src/index.ts
Both `KurtOpenAI` and `KurtVertexAI` support multiple different models, selectable by name. This change adds an `isSupportedModel` function to both, so that users of the libraries can easily check if a given string matches a supported model name.
This function also acts as a type guard that can
be used from TypeScript to convert a string conditionally into a strongly typed type union of model ames.
Also, the exports for these packages have been expanded to include additional types like the aforementioned type union of model names.
These new features make it easier to build applications that have some functions dealing with model name strings in deciding which Kurt adapter to create, helping with Kurt's central mission to make it easy to build applications which switch between different …
> feat: add static functions on the adapters to check for compatible model names

- package.json
- packages/kurt-open-ai/package.json
- packages/kurt-vertex-ai/package.json
- pnpm-lock.yaml
Prior to this commit, the adapter libraries were depending on a workspace version of Kurt. This is unfit for publishing, because downstream users of the libraries won't have Kurt in their workspace.
We need to depend on fixed versions of Kurt and then use pnpm overrides to make it use the workspace version of Kurt in local development.
This commit does that fix.
> fix: make the adapters depend on non-workspace Kurt version

- .github/workflows/ci.yaml
For packages that depend on other packages in the monorepo, we are explicitly tracking by hand the minimum supported version of the intra-monorepo dependency, in the package.json `dependencies` list, and then for local development we are overriding that with pnpm overrides to allow experimentation across packages without publishing.
Tracking the minimum version explicitly (as opposed to always using the latest version as `pnpm publish` does) has the benefit that the user is not forced to update the common dependency unless it is absolutely necessary. This may help prevent some forms of "dependency hell" for users.
However, it has the downside that we might forget to update the version in the dependency list in some cases, and risk publishing a broken package as a result.
This PR prevents …
> ci: run tests also without any pnpm overrides

- packages/kurt/spec/FakeAdapterV1.ts
- packages/kurt/spec/Kurt.spec.ts
- packages/kurt/src/Kurt.ts
- packages/kurt/src/KurtAdapter.ts
This commit adds a `KurtSamplingOptions` type with various tweakable values and a `KurtSamplingOptionsDefault` constant with the default values to use when not given.
The `sampling` key can be used to specify sampling options on creation, and/or on individual generate calls. See the docs and tests for more details on what settings are possible and how they behave.
A future PR will update the adapter libraries to start making use of these values.
> feat: add `KurtSamplingOptions`, for tweaking output sampling details

- packages/kurt-open-ai/spec/KurtOpenAI.spec.ts
- packages/kurt-open-ai/src/KurtOpenAI.ts
This model was just released this week, and is said to be cheaper and faster, while still performing well.
The docs say it can do function calling, so it is being added here as supported by Kurt.
> feat: add new OpenAI model: gpt-4o

- packages/kurt-vertex-ai/spec/KurtVertexAI.spec.ts
- packages/kurt-vertex-ai/src/KurtVertexAI.ts
VertexAI has quietly changed the behavior of how the "final" event in a stream is represented. Previously, VertexAI would mark the stop reason on the same event as the final chunk of text or function call. Now VertexAI is sending a separate stop event with empty text, which was breaking our mechanism for handling tool calls.
This PR updates the tests and our event handling logic to account for this change in behavior.
> fix: account for changes in VertexAI chunking behavior

- packages/kurt-open-ai/spec/generateNaturalLanguage.spec.ts
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateNaturalLanguage_says_hello.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateNaturalLanguage_writes_a_haiku_with_high_temperature.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateStructuredData_says_hello.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(after_tool_call).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(with_tool_call).yaml
- packages/kurt-open-ai/src/KurtOpenAI.ts
- packages/kurt-vertex-ai/spec/generateNaturalLanguage.spec.ts
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateNaturalLanguage_says_hello.yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateNaturalLanguage_writes_a_haiku_with_high_temperature.yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateStructuredData_says_hello_(response_format_1).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateStructuredData_says_hello_(response_format_2).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateStructuredData_says_hello_(response_format_3).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(after_tool_call).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(with_tool_call).yaml
- packages/kurt-vertex-ai/src/KurtVertexAI.ts
This is a followup to PR #24, which added `KurtSamplingOptions` to the `Kurt` class.
Now, with this PR, the LLM-specific adapters (`KurtOpenAI` and `KurtVertexAI`) will now pass these options along to the underlying LLM provider, in the appropriate adapted way.
This commit also adds tests which demonstrate the passing of these options.
> feat: pass KurtSamplingOptions to the underlying LLM provider

- packages/kurt-open-ai/spec/generateWithOptionalTools.spec.ts
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(after_parallel_tool_calls).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(with_parallel_tool_calls).yaml
- packages/kurt-open-ai/src/KurtOpenAI.ts
This commit updates the `KurtOpenAI` adapter to handle the case of multiple parallel tool calls from the LLM, when being used with the `generateWithOptionalTools` method of `Kurt`.
In theory it would make sense to handle this case for `generateStructuredData` too, but in practice I cannot get OpenAI to respond with parallel tool calls when we are using `tool_choice: { function: {...} }` as we do in that method - it seems as though this option prevents parallel tool calls. If we can get this behavior to surface in practice in the future we can add logic and tests to handle that case.
Note that this resolves part of issue #33 - it resolves it for the OpenAI adapter, but not the Vertex AI adapter.
> feat: support parallel tool calls in `KurtOpenAI` with `generateWithOptionalTools`

- packages/kurt-open-ai/package.json
- packages/kurt-vertex-ai/package.json
- packages/kurt/package.json
This commit sets the `homepage` and `repository` fields in each package's `package.json` to make this repository easily discoverable if starting from npm.
> fix: add missing repository information to `package.json`

- packages/kurt-open-ai/src/KurtOpenAI.ts
- packages/kurt-vertex-ai/spec/generateWithOptionalTools.spec.ts
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(after_parallel_tool_calls).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(with_parallel_tool_calls).yaml
- packages/kurt-vertex-ai/src/KurtVertexAI.ts
This commit updates the `KurtVertexAI` adapter to handle the case of multiple parallel tool calls from the LLM, when being used with the `generateWithOptionalTools` method of `Kurt`.
Similar to PR #35, this PR resolves part of issue #33
> feat: support parallel tool calls in `KurtVertexAI` with `generateWithOptionalTools`

- .github/workflows/ci.yaml
- package.json
- packages/kurt-open-ai/README.md
- packages/kurt-open-ai/package.json
- packages/kurt-vertex-ai/README.md
- packages/kurt-vertex-ai/package.json
- packages/kurt/package.json
- scripts/interpolate-example-code.sh
- turbo.json
This script will modify the given files (all CLI arguments passed to the script are interpreted as filenames) to interpolate example code from files.
It looks for lines that look like this:
[This example code](../path/to/file.ts) shows how to do X.
And replaces those occurrences to look like this:
This example code shows how to do X.
```ts
// Contents of ../path/to/file.ts
```
This simple hack allows us to keep our code examples in separate files (which are runnable and testable in CI), while still including them inline in the documentation that gets published to npmjs.org for the packages.
> chore: interpolate example code in README.md for each package

- examples/basic/package.json
- examples/basic/src/model-agnostic.ts
Created model agnostic example, using environment variables to pass in the model, then running through all 3 generation examples
> chore(examples): create model agnostic example

- examples/basic/package.json
- packages/kurt-open-ai/package.json
- packages/kurt-open-ai/spec/generateNaturalLanguage.spec.ts
- packages/kurt-open-ai/spec/generateWithOptionalTools.spec.ts
- packages/kurt-open-ai/spec/snapshots.ts
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateNaturalLanguage_says_hello.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateNaturalLanguage_writes_a_haiku_with_high_temperature.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateStructuredData_says_hello.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(after_parallel_tool_calls).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(after_tool_call).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(with_parallel_tool_calls).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(with_tool_call).yaml
- packages/kurt-open-ai/src/KurtOpenAI.ts
- packages/kurt-open-ai/src/OpenAI.types.ts
- pnpm-lock.yaml
This implements the new optional `metadata` field of the `KurtResult` interface to provide the total input and output tokens, as well as the system fingerprint string (used for checking whether determinism can be expected).
Note that this commit involves regenerating all the test snapshots because we are now capturing and relying on more from the upstream OpenAI responses.
> feat: add usage/fingerprint metadata to `KurtResult` for `KurtOpenAI` adapter.

- packages/kurt-vertex-ai/spec/generateNaturalLanguage.spec.ts
- packages/kurt-vertex-ai/spec/generateWithOptionalTools.spec.ts
- packages/kurt-vertex-ai/spec/snapshots.ts
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateNaturalLanguage_says_hello.yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateNaturalLanguage_writes_a_haiku_with_high_temperature.yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateStructuredData_says_hello_(response_format_1).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateStructuredData_says_hello_(response_format_2).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateStructuredData_says_hello_(response_format_3).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(after_parallel_tool_calls).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(after_tool_call).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(with_parallel_tool_calls).yaml
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateWithOptionalTools_calculator_(with_tool_call).yaml
- packages/kurt-vertex-ai/src/KurtVertexAI.ts
- packages/kurt-vertex-ai/src/VertexAI.types.ts
This implements the new optional `metadata` field of the `KurtResult` interface to provide the total input and output tokens. Note that no system fingerprint is available from Vertex AI's Gemini API, so that is omitted here. If it ever becomes available, we can add it.
Note that this commit involves regenerating all the test snapshots because we are now capturing and relying on more from the upstream Vertex AI responses.
> feat: add usage/fingerprint metadata to `KurtResult` for `KurtVertexAI` adapter

- packages/kurt-vertex-ai/spec/generateNaturalLanguage.spec.ts
- packages/kurt-vertex-ai/spec/snapshots/KurtVertexAI_generateNaturalLanguage_properly_formats_a_system_prompt_for_Vertex_AI.yaml
- packages/kurt-vertex-ai/src/KurtVertexAI.ts
Prior to this commit, system prompt messages were included by the `KurtVertexAI` as part of the `content` stream of messages. However, VertexAI requires system messages to be specified separately. This commit makes that change.
> fix: system prompt formatting for Vertex AI

- examples/basic/package.json
- examples/basic/src/cache.ts
- packages/kurt-cache/.gitignore
- packages/kurt-cache/.kurt-cache/test-retain/stub-ad557ba1818e8013f9e2fbc9598c034e263c96c5fe7edd491e75be8ce450f5c9.yaml
- packages/kurt-cache/README.md
- packages/kurt-cache/jest.config.js
- packages/kurt-cache/package.json
- packages/kurt-cache/spec/KurtCache.spec.ts
- packages/kurt-cache/src/KurtCache.ts
- packages/kurt-cache/src/index.ts
- packages/kurt-cache/tsconfig.json
- pnpm-lock.yaml
This will make it easy to work with LLMs in tests, without requiring any LLM connectivity/usage for running existing tests whose inner LLM responses are already cached.
> feat: add `kurt-cache` package with `KurtCache` adapter

- packages/kurt-cache/.kurt-cache/test-retain/stub-b8a5a99fa499ef332c4a599d5b1eff433fc0ee7cd6995e86fb7dbfd8b9ffe999.yaml
- packages/kurt/spec/Kurt.spec.ts
- packages/kurt/src/Kurt.ts
- packages/kurt/src/KurtError.ts
This maps to the new-ish `strict: true` feature of OpenAI which enables constrained token sampling, but has certain caveats that make it undesirable to turn on by default.
See issue #61 for more info.
Also adds `KurtCapabilityError` which adapters should throw to signal if they are missing this capability when it is requested (or any other capability expected by some part of the request).
> feat: add `forceSchemaConstrainedTokens` to `KurtSamplingOptions`

- examples/basic/package.json
- packages/kurt-open-ai/package.json
- packages/kurt-open-ai/spec/generateNaturalLanguage.spec.ts
- packages/kurt-open-ai/spec/generateStructuredData.spec.ts
- packages/kurt-open-ai/spec/generateWithOptionalTools.spec.ts
- packages/kurt-open-ai/spec/snapshots.ts
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateStructuredData_says_hello.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateStructuredData_says_hello_with_schema_constrained_tokens.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateStructuredData_says_hello_with_system_prompt.yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(after_parallel_tool_calls).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(with_parallel_tool_calls).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(with_strict_tool_call).yaml
- packages/kurt-open-ai/spec/snapshots/KurtOpenAI_generateWithOptionalTools_calculator_(with_tool_call).yaml
- packages/kurt-open-ai/src/KurtOpenAI.ts
- pnpm-lock.yaml
We also set JSON-constrained tokens by default for `generateStructuredData`.
This commit also updates the set of supported models to include the newer model snapshots. We also update the tests to allow for specifying different models per test, and to mostly use the newer models. This includes updating our snapshots in our unit tests to make sure everything is working suitably with the new models and changes to the OpenAI request format.
> feat: add support for schema-constrained tokens in `KurtOpenAI`

- packages/kurt-vertex-ai/spec/generateStructuredData.spec.ts
- packages/kurt-vertex-ai/src/KurtVertexAI.ts
Vertex AI is not yet capable of this feature, and we want to proactively warn the user that they cannot expect a schema conformance guarantee.
> fix: make KurtVertexAI properly throw KurtCapabilityError for the schema-constrained tokens case

- packages/kurt-cache/spec/KurtCache.spec.ts
- packages/kurt-cache/src/KurtCache.ts
This ensures that changing the option will correctly cause a cache miss. But leaving it at the default value of `false` won't change existing hashes because `false` is treated as "missing" in the `mayHash` internal function.
> fix: ensure `KurtCache` hashes the new `forceSchemaConstrainedTokens` option

- packages/kurt-cache/spec/KurtCache.spec.ts
- packages/kurt-cache/src/KurtCache.ts
Prior to this commit, that option was being silently dropped because it was neglected in the new object that gets sent to the internal adapter. This commit introduces a usage of the spread operator to ensure that no such options are dropped (while still allowing the replacement of other options).
> fix: correctly pass through the `forceTool` option inside `KurtCache.generateRawEvents`
